# Data base: RELATION DATABASE / NON-RELATIONAL

# CREATE: DATABASE -> TABLE
# READ:
# UPDATE:
# DELETE:
# CRUD

# CREATE
# INSERT: USE TO INSERT DATA INTO TABLE
    # insert into tablename table fileds and data
# READ: USE SELECT TO FETCH DATA FORM DB TABLE
# WHERE: 'SELECT DATA FORM TABLE WHERE NAME=DAKSH'
# ORDER BY: 'SELECT DATA FORM TABLE WHERE NAME=DAKSH ORDER BY PRICE DESC'
# UPDATE: UPDATE DATA FORM TABLE UPDATEDATA
# DELETE: DELETE DATA FORM TABLE CONDTION
# LIMIT: USING TO FETCH LIMMITED DATA 
# JOIN: JOIN MORE THEN ONE TABLE USING JOIN KEYWORD
    # INNER JOIN: LIKE SETS INTERSECTION
    # FULL JOIN: LIKE SETS UNION
    # LEFT JOIN: GET COMPLETE DATA OF TABLE A AND SIMILER DATA FROM TABLE B
    # RIGHT JOIN: SAME FROM RIGHT TABLE     


# mysql me hum query likhe hai

# DATABASE - GHAR
# TABLE - GHAR KA HISAB-KITAB
# NO. SAMAN DATE    NAME    PRICE
# -     -      -      -       -
# -     -      -      -       -
# -     -      -      -       -
# -     -      -      -       -
# -     -      -      -       -
# -     -      -      -       -

# FOR USING MYSQL WIHT PYTHON NEED TO INSTALL MYSQL PACKAGE
# python -m pip install mysql-connector-python

import mysql.connector

